---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-01-19T20:24:13Z"
  labels:
    app: vmware-vspc
  name: vmware-vspc
spec:
  containers:
  - command:
    - --config-file
    - /etc/vmware-vspc/vspc.conf
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: oci
    - name: DISTTAG
      value: f31container
    - name: FGC
      value: f31
    - name: HOSTNAME
    image: quay.io/jcallen/vmware-vspc:latest
    name: vmware-vspc
    ports:
    - containerPort: 13370
      hostPort: 13370
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
    workingDir: /
status: {}

